config/routes.rb
Rails.application.routes.draw do
  resources :high_school_scheds
  resources :schedules do
    collection do
      get :anos_iniciais   # Route for "Anos Iniciais"
      get :ensino_medio    # Route for "Ensino Médio"
    end
  end

  resources :school_classes
  resources :teachers
  resources :subjects
  resources :high_schools
  
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get 'home/about'
  root 'home#index'
  get '/subjects', to: 'subjects#index'
  patch '/subjects/:id', to: 'subjects#update'
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def ensinomedio
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="footer">
      <p>&copy; <%= Time.now.year %> Carvalhio | Todos os direitos reservados</p>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd">
  <div class="container-fluid">
     <%= link_to 'Gest', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Início', root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Professores", teachers_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Comp. Curriculares", subjects_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "Turmas", school_classes_path, class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="testesDropdown" data-bs-toggle="dropdown" aria-expanded="false">
             Cronograma
          </a>
          <ul class="dropdown-menu" aria-labelledby="testesDropdown">
            <li><a class="dropdown-item" href="#">• Ensino Infantil</a></li>
            <li><%= link_to "• Anos Iniciais".html_safe, anos_iniciais_schedules_path, class:"dropdown-item" %></li>
            <li><%= link_to "• E.F. Anos Finais".html_safe, schedules_path, class:"dropdown-item" %></li>
            <li><%= link_to "• Ensino Médio".html_safe, high_schools_path, class:"dropdown-item" %></li>
            <li><%= link_to "• Pré-Universitário".html_safe, high_schools_path, class:"dropdown-item" %></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="testesDropdown" data-bs-toggle="dropdown" aria-expanded="false">
     Manual
  </a>
  <ul class="dropdown-menu" aria-labelledby="testesDropdown">
    <li><a class="dropdown-item" href="#">• Ensino Infantil</a></li>
    <li><%= link_to "• Anos Iniciais".html_safe, anos_iniciais_schedules_path, class:"dropdown-item" %></li>
    <li><%= link_to "• E.F. Anos Finais".html_safe, schedules_path, class:"dropdown-item" %></li>
    <li><%= link_to "• Ensino Médio".html_safe, high_schools_path, class:"dropdown-item" %></li>
    <li><%= link_to "• Pré-Universitário".html_safe, high_schools_path, class:"dropdown-item" %></li>
  </ul>
</li>

        <li class="nav-item">
           <%= link_to "Loja", school_classes_path, class:"nav-link" %>
        </li>
      
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h6 class="text-center">1ª Etapa</h6>
<table class="table table-sm table-bordered border-primary">
  <thead>
    <tr>
      <th class="text-center" scope="col">Aplicação</th>
      <th class="text-center" scope="col">Data</th>
      <th class="text-center" scope="col">Comp. Curriculares</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="text-center" rowspan="4" style="vertical-align: middle;">Parciais<br>6º ano e 7º ano</td>
      <td class="text-center">23/01</td>
      <td class="text-center">Redação</td>
    </tr>
    <tr>
      <td class="text-center">30/01</td>
      <td class="text-center">Matemática</td>
    </tr>
    <tr>
      
      <td class="text-center">25/01</td>
      <td class="text-center">Português</td>
    </tr>
    <tr>
      <td class="text-center">31/01</td>
      <td class="text-center">Inglês</td>
    </tr>
  </tbody>
</table>
<br>

app/views/home/index.html.erb
<h1>Bem-vindo</h1>
<p></p>