config/routes.rb
Rails.application.routes.draw do
  resources :high_school_scheds
  resources :schedules do
    collection do
      get :anos_iniciais   # Route for "Anos Iniciais"
      get :ensino_medio    # Route for "Ensino Médio"
    end
  end

  resources :school_classes
  resources :teachers
  resources :subjects
  resources :high_schools
  
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get 'home/about'
  root 'home#index'
  get '/subjects', to: 'subjects#index'
  patch '/subjects/:id', to: 'subjects#update'
   
end

app/models/subject.rb
class Subject < ApplicationRecord
	belongs_to :teacher, optional: true
    has_many :high_school_subjects
    has_many :high_schools, through: :high_school_subjects
    
     has_and_belongs_to_many :teachers
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	before_action :set_subject, only: [:show, :edit, :update, :destroy]

  def index
    @subjects = Subject.all
  end

  def show; end

  def new
    @subject = Subject.new
  end

  def edit 
      @subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to @subject, notice: 'Disciplina criada com sucesso!'
    else
      render :new
    end
  end

  def update
      @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      redirect_to subjects_path, notice: 'Disciplina atualizada com sucesso!'
    else
      render :edit
    end
  end

  def destroy
    @subject.destroy
    redirect_to subjects_url, notice: 'Disciplina excluída com sucesso!'
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:subject_name, :teacher_id)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/edit.html.erb
<h1>Editar Disciplina</h1>

<%= form_for(@subject) do |form| %>
  <%= form.label :subject_name %>
  <%= form.text_field :subject_name %>

  <%= form.label :teacher_id %>
  <%= form.collection_select :teacher_id, Teacher.all, :id, :name %>

  <%= form.submit 'Atualizar Disciplina' %>
<% end %>

app/views/subjects/index.html.erb
<h6>Componentes Curriculares</h6>

<%= link_to 'Novo Componente Curricular', new_subject_path, class: 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Comp. Curricular</th>
      <th>Professor</th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.subject_name %></td>
        <td><%= subject.teacher&.name || "-" %></td>
        <td>
          <%= link_to 'Editar', edit_subject_path(subject) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>